fixtures:
  repositories:
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '4.11.0'
    inifile:
      repo: "https://github.com/puppetlabs/puppetlabs-inifile.git"
      ref: '1.4.3'

  symlinks:
    cutover: "#{source_dir}"
